import Head from 'next/head'
import Header from '../components/Header/Header'
import styles from '../styles/crew.module.scss'

export default function Destination() {
  return (
    <>
      <Head>
        <title>Space</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Bellefair&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Barlow&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.test}>
        <Header></Header>
        
      </main>
    </>
  )
}
