import Head from 'next/head'
import Destinationcontent from '../../components/destinationcontent/destinationcontent'
import Header from '../../components/Header/Header'
import styles from '../../styles/destination.module.scss'

export default function Moon() {
  return (
    <>
      <Head>
        <title>Space</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Bellefair&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Barlow&display=swap" rel="stylesheet"></link>
      </Head>
      
      <main className={styles.test}>
          <Header></Header>
          <Destinationcontent></Destinationcontent>
          
      </main>
    </>
  )
}
